### ISSUE TITLE
comparison vs map

### ISSUE THREAD

**Issue by jojo05** [sean-public/skiplist-survey#1]
Hi,

It would be useful to also include a map in the comparison, to understand at what point the skiplist provides faster inserts
Thanks

**Comment by sangelone** [comment]
Do you mean populate a list with *n* items and then record the time to insert at every position? Like so:

1. create list of *n* items
2. for every index [0,n], record time to insert an element
3. remove the new element so the list stays the same size

**Comment by sean-public** [comment]
Will look into adding more insightful benchmarks to record. For now, you can imagine that the insert timing would look the same at each position as it would in the "worst case inserts" for a list of that size, which I've already recorded.

**Comment by jojo05** [comment]
Hi,
I apologize for not explaining better. I am interested in using a skip-list as a dictionary (string->int) for fast inserts O(log(n)) vs O(n*log(n)) for map.

 Does your skip-list or any other support string keys? If not, what other structure do you suggest. I might also check ART (adaptive radix tr.)
 
Thanks

**Comment by sean-public** [comment]
I note the accepted key types in the README. The best of the bunch for ease of use, accepting strings as keys, and reliable speed is https://github.com/huandu/skiplist -- look at the tests to see how to use `string->int`.
